# Generated by Django 5.2.1 on 2025-05-11 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='medico',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='turnos_medico', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='turno',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos_paciente', to=settings.AUTH_USER_MODEL),
        ),
    ]
